# Site settings
title: Hi, I'm Vineeth.
description: Vineeth Pydi's professional portfolio 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site

# User settings
username: Vineeth Pydi
user_title:
user_job_title: Data Professional
email: vineeth299 [at] hotmail.com
github_username:  vineeth-pydi

exclude: ['package.json', 'src' , 'node_modules']
